### ISSUE TITLE
Would you be amenable to allowing anonymous access?

### ISSUE THREAD

**Issue by packy** [gnustavo/JIRA-REST#11]
Hi, I'm the author of the module JIRA::REST::Class, which uses your module to access a JIRA server and then represent JIRA's entities as Perl object classes instead of hashed.

I just got [an inquiry](https://github.com/packy/JIRA-REST-Class/issues/2) about the possibility of using my class to anonymously access public JIRA APIs (like jira.atlassian.com).  I'm wondering if you'd be willing to entertain a pull request to allow that.  If so, I'll fork and write up a change for you to look at.

**Comment by gnustavo** [comment]
Sure, Packy. Give it a shot and we'll discuss it.

Latelly I was thinking about a new interface for new so that I could accomodate other parameters in the future without breaking compatibility. Something like accepting a hash-ref with keys naming the arguments. Feel free to come up with something like this if it makes sense to you.

Also, JIRA::REST still doesn't have any tests besides. Being able to use anonymous REST calls would allow me to implement a few tests using Atlassian's own JIRA instance.

**Comment by packy** [comment]
Exactly.  I borrowed code from REST::Client to implement a lightweight
pseudo-JIRA server for my own tests (thus allowing me to control the data
being returned), but being able to test against Atlassian's instance would
definitely help with integration testing.
